### ISSUE TITLE
[FEATURE] List View

### ISSUE THREAD

**Issue by Arthi-chaud** [AnonymusRaccoon/Kyoo#63]
**Describe the feature you'd like**
Display the shows like a list, instead of a poster list. It is handy when we want to look for a title instead of a poster.

It could look something like this:
![image](https://user-images.githubusercontent.com/60505370/152792429-5781c80c-2d3f-429e-a360-cec690dd483f.png)

**Comment by AnonymusRaccoon** [comment]
Do you have other sites as examples? I tried to create one but I find the view ugly.
![image](https://user-images.githubusercontent.com/32224410/191756657-2cb15c2d-5a72-40b0-bb5f-e86357639667.png)

**Comment by Arthi-chaud** [comment]
The spacing induced by the poster really makes the page look empty.
Maybe you could remove that illustration and add a third field? This would reduce the lines' height.
Or you can just limit the poster's height, but that would make it too small to be legible, and therefore useless.
So I suggest that you remove the poster and add the studio or filmmaker (not sure if this is compatible w/ tv shows?)
