### ISSUE TITLE
[FEATURE]  Add a 'Setting-up' Section to Readme

### ISSUE THREAD

**Issue by Arthi-chaud** [AnonymusRaccoon/Kyoo#65]
**Is your feature request related to a problem? If yes, please describe.**
When we want to use Kyoo for the first time, we don't know what to do.

**Describe the feature you'd like**
Add a 'Set up' section and some requirements in the main README.md

**Describe alternatives you've considered**
Have AnonymusRaccoon next to you

**Comment by Octopus773** [comment]
I hung myself while trying to understand Kyoos setup

**Comment by Octopus773** [comment]
#UXMatters
#LambdaUsersMatters

**Comment by AnonymusRaccoon** [comment]
I agree that this is a must have soon x)

**Comment by AnonymusRaccoon** [comment]
Fixed by #74, having a nice UI will be tracked by #75.
